/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const swe_julday: (a: number, b: number, c: number, d: number, e: number) => number;
export const swe_revjul: (a: number, b: number) => any;
export const swe_calc_ut: (a: number, b: number, c: number) => any;
export const swe_houses: (a: number, b: number, c: number, d: number, e: number) => any;
export const swe_get_planet_name: (a: number) => [number, number];
export const __wbg_se_free: (a: number, b: number) => void;
export const se_MERCURY: () => number;
export const se_VENUS: () => number;
export const se_MARS: () => number;
export const se_JUPITER: () => number;
export const se_SATURN: () => number;
export const se_URANUS: () => number;
export const se_NEPTUNE: () => number;
export const se_PLUTO: () => number;
export const se_MEAN_NODE: () => number;
export const se_TRUE_NODE: () => number;
export const se_GREG_CAL: () => number;
export const se_JUL_CAL: () => number;
export const se_FLG_SPEED: () => number;
export const swe_calc_ut_batch: (a: number, b: number, c: number, d: number) => any;
export const swe_calc_ut_all: (a: number, b: number) => any;
export const getAllPlanetaryPositions: (a: number) => any;
export const getNatalChart: (a: number, b: number, c: number) => any;
export const getMoonPhase: (a: number) => [number, number];
export const getSignFromLongitude: (a: number) => [number, number];
export const isVoidOfCourseMoon: (a: number) => number;
export const getPlanetaryHourRuler: (a: number, b: number, c: number, d: number) => [number, number];
export const computeTransitAspects: (a: number, b: any) => any;
export const computeMundaneAspects: (a: number) => any;
export const computeTransitAspectsWithOrbs: (a: number, b: any, c: any) => any;
export const computeMundaneAspectsWithOrbs: (a: number, b: any) => any;
export const computeNatalAspectsWithOrbs: (a: number, b: number, c: number, d: any) => any;
export const calculateChart: (a: number, b: number, c: number, d: number, e: number, f: number) => any;
export const getPlanetInHouse: (a: number, b: number, c: number) => number;
export const se_MOON: () => number;
export const se_SUN: () => number;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __wbindgen_exn_store: (a: number) => void;
export const __externref_table_alloc: () => number;
export const __wbindgen_externrefs: WebAssembly.Table;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __wbindgen_start: () => void;
